name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out this repo
      - uses: actions/checkout@v3

      # Set-up Nix stuff
      - uses: aldoborrero/use-nix-action@v2
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      # Actually reproducibly build this shit
      - name: Build Glove80 combined firmware
        run: nom build

      # Release if pushed with tag!
      - name: Upload release of build artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./result/glove80.uf2
